### ISSUE TITLE
Displayed Palico levels are 1 lower than actual value

### ISSUE THREAD

**Issue by Deozaan** [ezapm/APMMHXSaveEditor#2]
The Palico Editor shows the level of Palicos as being one level lower than they actually are. Take a look at the screenshot:

![palico differences](https://cloud.githubusercontent.com/assets/227734/17377970/651d5068-5979-11e6-990d-cd79419cdf8e.png)

Palico Editor shows Sleepy on level 18 with 15811 XP.
Palico Check Tool shows Sleepy on level 19 with 15811 XP.

**Comment by ezapm** [comment]
Will fix later tonight! Thanks.

**Comment by ezapm** [comment]
Fixed in v0.11c! Thanks again for reporting, I'll close this in 24 hours if there's nothing else to add.
