### ISSUE TITLE
"Beruna" should be "Bherna"

### ISSUE THREAD

**Issue by Deozaan** [ezapm/APMMHXSaveEditor#3]
Maybe the town names are different in MHX compared to MHG, but in MHG the main town is called Bherna.

And the "Academy" is called the "Wycademy" instead.

**Comment by ezapm** [comment]
I'll fix that next update. Thanks!

**Comment by ezapm** [comment]
Text fixes should be fixed in the v0.12 build. I'll close this within 24 hours if there's nothing to add. Thanks again for reporting!
